### ISSUE TITLE
Plugin crashes/doesn't display when choosing IST

### ISSUE THREAD

**Issue by Sushantdbg** [jonathanlermitage/ij-worldclock#1]
### Plugin refuses to show anything when only IST is selected

![1](https://user-images.githubusercontent.com/86154075/165144669-99abcdf7-4950-4d63-9b72-01e12bf6fd2c.png)

### In case of adding up something up it does show, just only the new one selected and ignores IST

![2](https://user-images.githubusercontent.com/86154075/165145024-e0ccef86-d476-4c86-9b45-28766496214e.png)

**Comment by Sushantdbg** [comment]
The below was the error message thrown at reboot of Webstorm

```text
java.time.zone.ZoneRulesException: Unknown time-zone ID: IST
	at java.base/java.time.zone.ZoneRulesProvider.getProvider(ZoneRulesProvider.java:279)
	at java.base/java.time.zone.ZoneRulesProvider.getRules(ZoneRulesProvider.java:234)
	at java.base/java.time.ZoneRegion.ofId(ZoneRegion.java:120)
	at java.base/java.time.ZoneId.of(ZoneId.java:408)
	at java.base/java.time.ZoneId.of(ZoneId.java:356)
	at lermitage.intellij.worldclock.statusbar.ClockPresentation.getSelectedValue(ClockPresentation.java:55)
	at com.intellij.openapi.wm.impl.status.widget.StatusBarWidgetWrapper$MultipleTextValues.<init>(StatusBarWidgetWrapper.java:60)
	at com.intellij.openapi.wm.impl.status.widget.StatusBarWidgetWrapper.wrap(StatusBarWidgetWrapper.java:36)
	at com.intellij.openapi.wm.impl.status.IdeStatusBarImpl.wrap(IdeStatusBarImpl.java:532)
	at com.intellij.openapi.wm.impl.status.IdeStatusBarImpl.addWidget(IdeStatusBarImpl.java:335)
	at com.intellij.openapi.wm.impl.status.IdeStatusBarImpl.lambda$addWidget$1(IdeStatusBarImpl.java:223)
	at com.intellij.util.ui.EdtInvocationManager.invokeLaterIfNeeded(EdtInvocationManager.java:101)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2125)
	at com.intellij.openapi.wm.impl.status.IdeStatusBarImpl.addWidget(IdeStatusBarImpl.java:223)
	at com.intellij.openapi.wm.impl.status.IdeStatusBarImpl.addWidget(IdeStatusBarImpl.java:235)
	at com.intellij.openapi.wm.impl.status.widget.StatusBarWidgetsManager.lambda$enableWidget$1(StatusBarWidgetsManager.java:152)
	at com.intellij.util.ui.EdtInvocationManager.invokeLaterIfNeeded(EdtInvocationManager.java:101)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2125)
	at com.intellij.openapi.wm.impl.status.widget.StatusBarWidgetsManager.enableWidget(StatusBarWidgetsManager.java:145)
	at com.intellij.openapi.wm.impl.status.widget.StatusBarWidgetsManager.updateWidget(StatusBarWidgetsManager.java:92)
	at com.intellij.openapi.wm.impl.status.widget.StatusBarWidgetsManager.updateAllWidgets(StatusBarWidgetsManager.java:64)
	at com.intellij.openapi.wm.impl.status.widget.StatusBarWidgetsManager.installPendingWidgets(StatusBarWidgetsManager.java:215)
	at com.intellij.openapi.wm.impl.ProjectFrameHelper.installDefaultProjectStatusBarWidgets(ProjectFrameHelper.java:412)
	at com.intellij.openapi.wm.impl.ProjectFrameHelper.setProject(ProjectFrameHelper.java:395)
	at com.intellij.openapi.wm.impl.WindowManagerImpl.assignFrame(WindowManagerImpl.kt:286)
	at com.intellij.openapi.project.impl.ProjectUiFrameAllocator$projectLoaded$1.run(ProjectFrameAllocator.kt:174)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by jonathanlermitage** [comment]
Good catch. Some timezones seem to be invalid, or ambiguous. `IST` could be Irish, Indian or Israel Standard Time. I will remove these entries. They are provided by the icu4j library (used to find timezones for each country code/flag), but they are not supported by most JVMs.

**Comment by Sushantdbg** [comment]
> Good catch. Some timezones seem to be invalid, or ambiguous. `IST` could be Irish, Indian or Israel Standard Time. I will remove these entries. They are provided by the icu4j library (used to find timezones for each country code/flag), but they are not supported by most JVMs.

That's nice of you; The reason to choose IST was to get Indian Standard Time as there's no such entry like Asia/Kolkata or Asia/Delhi or Asia/India, can you look into that as well.

Thank you 👍

**Comment by jonathanlermitage** [comment]
Sure!  
Some timezones are missing because I am using ICU4J in order to get a list of timezones for each country (2-digit codes). Unfortunately, ICU4J is not up to date, that's why Asia/Kolkata is missing.  

I will replace ICU4J by some static code, and I will find missing timezones here: https://github.com/eggert/tz/blob/main/zone.tab , it sounds promising. I will let you know when it's done.

**Comment by jonathanlermitage** [comment]
@Sushantdbg can you try this release? 
[WorldClock-1.1.0.zip](https://github.com/jonathanlermitage/ij-worldclock/files/8599396/WorldClock-1.1.0.zip)
Thx!

**Comment by Sushantdbg** [comment]
> @Sushantdbg can you try this release?

## Tried it out works nice 👍

![image](https://user-images.githubusercontent.com/86154075/166180405-72cdb53d-32b9-49ac-85b3-6e0e2c58621d.png)

**Comment by jonathanlermitage** [comment]
Thx! I will publish the new release this weekend.
